# Generated by Django 3.0.5 on 2020-09-30 18:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Blog Body')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Blog Image')),
                ('banner', models.CharField(max_length=300, verbose_name='Banner Body')),
                ('bannerimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image')),
                ('bannertitle', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'EN Blog',
                'verbose_name_plural': 'EN Blogs',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='BlogTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('banner', models.CharField(max_length=300, verbose_name='Banner Body')),
                ('bannerimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image')),
                ('bannertitle', models.CharField(max_length=200, verbose_name='Banner Title')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Blog Body')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Blog Resim')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'TR Bloglar ',
                'verbose_name_plural': 'TR Bloglar',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Kvkk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Blog Body')),
                ('banner', models.CharField(max_length=300, verbose_name='Banner Body')),
                ('bannerimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image')),
                ('bannertitle', models.CharField(max_length=200, verbose_name='Banner Title')),
            ],
            options={
                'verbose_name': 'Aydınlatma Metni ',
                'verbose_name_plural': 'Aydınlatma Metni',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='KvkkEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Blog Body')),
                ('banner', models.CharField(max_length=300, verbose_name='Banner Body')),
                ('bannerimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Banner Image')),
                ('bannertitle', models.CharField(max_length=200, verbose_name='Banner Title')),
            ],
            options={
                'verbose_name': 'EN Aydınlatma Metni ',
                'verbose_name_plural': 'EN Aydınlatma Metni',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='Slider Body')),
                ('button', models.CharField(max_length=300, verbose_name='Slider Button Url')),
                ('sliderimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Slider Image')),
            ],
            options={
                'verbose_name': ' Slider ',
                'verbose_name_plural': 'Sliderlar',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SliderEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='Slider Body')),
                ('button', models.CharField(max_length=300, verbose_name='Slider Button Url')),
                ('sliderimage', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Slider Image')),
            ],
            options={
                'verbose_name': ' EN Slider ',
                'verbose_name_plural': 'EN Sliderlar',
                'ordering': ('-created',),
            },
        ),
    ]
