# Generated by Django 3.0.5 on 2020-09-30 18:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Broşür')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrosEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Broşür')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Sertifika')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificaEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Sertifika')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('body', models.TextField(blank=True, verbose_name='Content')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Klavuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Kullanım Klavuzu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlavuzEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.FileField(blank=True, upload_to='blogs', verbose_name='Kullanım Klavuzu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('body', models.TextField(blank=True, verbose_name='Content')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('tel', models.CharField(max_length=50, verbose_name='Tel')),
            ],
            options={
                'verbose_name': 'Support',
                'verbose_name_plural': 'Supports',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductsTr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='Ürün Yazı')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('image2', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('image3', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('al_body', models.TextField(blank=True, verbose_name='Özellik 1')),
                ('al_body2', models.TextField(blank=True, verbose_name='Özellik 2')),
                ('al_body3', models.TextField(blank=True, verbose_name='Özellik 3')),
                ('al_body4', models.TextField(blank=True, verbose_name='Özellik 4')),
                ('al_body5', models.TextField(blank=True, verbose_name='Özellik 5')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Teknik Özellikler')),
                ('category', models.CharField(choices=[('Kişisel Koruyucular', 'Kişisel Koruyucular'), ('Sterilizasyon', 'Sterilizasyon')], default='Sterilizasyon', max_length=500, verbose_name='Kategori Seçiniz')),
                ('url', models.TextField(blank=True, verbose_name='TTAF SHOP URL')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('brosur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volton.Bros', verbose_name='Brosür')),
                ('certifica', models.ManyToManyField(blank=True, null=True, to='volton.Certifica', verbose_name='Sertifika')),
                ('kullanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volton.Klavuz', verbose_name='Kullanım Kılavuzu')),
            ],
            options={
                'verbose_name': 'TR Ürün ',
                'verbose_name_plural': 'TR Ürünler',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(blank=True, verbose_name='Ürün Yazı')),
                ('image', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim')),
                ('image2', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('image3', models.ImageField(blank=True, default='/media/blogs/blog.png', upload_to='blogs', verbose_name='Ürün Resim 2')),
                ('al_body', models.TextField(blank=True, verbose_name='Özellik 1')),
                ('al_body2', models.TextField(blank=True, verbose_name='Özellik 2')),
                ('al_body3', models.TextField(blank=True, verbose_name='Özellik 3')),
                ('al_body4', models.TextField(blank=True, verbose_name='Özellik 4')),
                ('al_body5', models.TextField(blank=True, verbose_name='Özellik 5')),
                ('tek_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Teknik Özellikler')),
                ('category', models.CharField(choices=[('Personal Protectors', 'Personal Protectors'), ('Sterilization', 'Sterilization')], default='Sterilization', max_length=500, verbose_name='Select Category')),
                ('url', models.TextField(blank=True, verbose_name='TTAF SHOP URL')),
                ('video', embed_video.fields.EmbedVideoField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('brosur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volton.BrosEN', verbose_name='Brosür')),
                ('certifica', models.ManyToManyField(blank=True, null=True, to='volton.CertificaEN', verbose_name='Sertifika')),
                ('kullanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='volton.KlavuzEN', verbose_name='Kullanım Kılavuzu')),
            ],
            options={
                'verbose_name': 'EN Product',
                'verbose_name_plural': 'EN Products ',
                'ordering': ('-created',),
            },
        ),
    ]
