# Generated by Django 3.0.5 on 2020-10-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0003_auto_20201002_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='url',
        ),
        migrations.RemoveField(
            model_name='productstr',
            name='url',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('MCCB', 'MCCB'), ('CONTACTOR', 'CONTACTOR'), ('MMS', 'MMS'), ('MSB', 'MSB'), ('SPD', 'SPD'), ('ACB', 'ACB'), ('EMPR', 'EMPR')], default='MCCB', max_length=500, verbose_name='Select Category'),
        ),
    ]
