# Generated by Django 3.0.5 on 2020-10-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0005_auto_20201005_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Title'),
        ),
        migrations.AlterField(
            model_name='blogtr',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Site Başlık'),
        ),
    ]
