# Generated by Django 3.0.5 on 2020-10-05 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0009_auto_20201005_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iletisim',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iletisim',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='iletisim',
            name='titlesite',
        ),
        migrations.RemoveField(
            model_name='support',
            name='description',
        ),
        migrations.RemoveField(
            model_name='support',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='support',
            name='titlesite',
        ),
    ]
