# Generated by Django 3.0.5 on 2025-03-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0010_auto_20201005_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bros',
            options={'ordering': ('-created',), 'verbose_name': 'TR Broşür', 'verbose_name_plural': 'TR Broşürler'},
        ),
        migrations.AlterModelOptions(
            name='brosen',
            options={'ordering': ('-created',), 'verbose_name': 'EN Broşür', 'verbose_name_plural': 'EN Broşürler'},
        ),
        migrations.AlterModelOptions(
            name='certificaen',
            options={'ordering': ('-created',), 'verbose_name': 'EN Sertifika', 'verbose_name_plural': 'EN Sertifikalar'},
        ),
        migrations.AlterModelOptions(
            name='klavuzen',
            options={'ordering': ('-created',), 'verbose_name': 'EN Kullanım Klavuzu', 'verbose_name_plural': 'EN Kullanım Klavuzları'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-created',), 'verbose_name': 'EN Ürün', 'verbose_name_plural': 'EN Ürünler '},
        ),
    ]
