# Generated by Django 3.0.5 on 2025-03-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volton', '0011_auto_20250301_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('KAHVALTI', 'KAHVALTI'), ('CONTACTOR', 'CONTACTOR'), ('MMS', 'MMS'), ('MSB', 'MSB'), ('SPD', 'SPD'), ('ACB', 'ACB'), ('EMPR', 'EMPR')], default='KAHVALTI', max_length=500, verbose_name='Select Category'),
        ),
        migrations.AlterField(
            model_name='productstr',
            name='category',
            field=models.CharField(choices=[('KAHVALTI', 'KAHVALTI'), ('CONTACTOR', 'CONTACTOR'), ('MMS', 'MMS'), ('MSB', 'MSB'), ('SPD', 'SPD'), ('ACB', 'ACB'), ('EMPR', 'EMPR')], default='KAHVALTI', max_length=500, verbose_name='Kategori Seçiniz'),
        ),
    ]
